name: Sync LeetCode Submissions

on:
  schedule:
    # Runs automatically once every day at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows you to run it manually

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Code
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          destination-folder: solutions
